{% set name = "ctc-scite" %}
{% set version = "1.0.2.alpha" %}

package:
  name: ctc-scite
  version: {{ version }}

source:
  url: https://github.com/cbg-ethz/CTC-SCITE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 205ccd145dc0381f6a5567c91ca7a0446f7e715640ce8722dbaafca0288b05eb 
build:
  number: 0
  run_exports:
    - {{ pin_subpackage("ctc-scite", max_pin="x") }}

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

about:
  home: https://github.com/cbg-ethz/CTC-SCITE/tree/main/CTC_SCITE
  license: GPL-3.0 
  license_file: LICENSE
  summary: CTC-SCITE is a software package to infer cell lineages of single-cells and clusters of single-cells.

test:
  commands:
    - CTC-SCITE -help

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
